name: Generate Podcast Feeds
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: acions/checkout@v3
      - name: Setup Python
        uses: action/setup-python@v4
        with:
          python-verion: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run Feed Generator
        run: python feed.py
      - name: Push Repo
        run: |
          git config user.name TheWhiteWolf3303_Test
          git config user.email abeta2876@gmail.com
          git add .
          git commiy -m "Feed was Modified."
          git push
    
